postgres_db:
  user: program
  password: test
  db_name: reservations             # postgres
  host: reservations
  port: 5432

reservation_app:
  host: "0.0.0.0"
  external_ip: "212.233.72.15"
  prefix: "/api/v1"
  port: 8070
  log_level: "info"
  reload: True
